name: Render R Markdown Report

on:
  push:
    branches: [main, master]
    paths:
      - '**.Rmd'
      - '.github/workflows/render-rmd.yml'
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libudunits2-dev

      - name: Install R packages
        run: |
          install.packages(c(
            "rmarkdown",
            "knitr",
            "biomod2",
            "raster",
            "dismo",
            "sp",
            "dplyr",
            "maxnet"
          ), repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Render R Markdown
        run: |
          rmarkdown::render(
            "Cretan_date_palm_Berkem_Toprak_Elmaci.Rmd",
            output_file = "index.html"
          )
        shell: Rscript {0}

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-report
          path: index.html
          retention-days: 30

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          include_files: index.html
